INFO 2023-07-04 16:29:52,536 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:29:52,649 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:29:52,754 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:29:52,858 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:29:52,964 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:29:53,070 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:29:55,134 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:29:55,181 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:29:55,289 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:29:55,692 [main.py:captureConfigX:51] xe2_04-07-23_16_29_55.txt
INFO 2023-07-04 16:29:55,768 [main.py:captureConfigX:51] xe1_04-07-23_16_29_55.txt
INFO 2023-07-04 16:29:55,985 [main.py:captureConfigX:51] xe3_04-07-23_16_29_55.txt
ERROR 2023-07-04 16:30:04,282 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:30:04,434 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:30:25,148 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:30:25,151 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:41:32,742 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:41:32,848 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:41:32,953 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:41:33,061 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:41:33,172 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:41:33,290 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:41:35,124 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:41:35,166 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:41:35,292 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:41:35,657 [main.py:captureConfigX:51] xe2_04-07-23_16_41_35.txt
INFO 2023-07-04 16:41:35,663 [main.py:captureConfigX:51] xe1_04-07-23_16_41_35.txt
INFO 2023-07-04 16:41:35,895 [main.py:captureConfigX:51] xe3_04-07-23_16_41_35.txt
ERROR 2023-07-04 16:41:44,406 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:41:44,518 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:42:05,366 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:42:05,369 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:43:05,672 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:43:05,775 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:43:05,881 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:43:05,986 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:43:06,092 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:43:06,195 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:43:08,200 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:43:08,313 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:43:08,372 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:43:08,772 [main.py:captureConfigX:51] xe1_04-07-23_16_43_08.txt
INFO 2023-07-04 16:43:08,854 [main.py:captureConfigX:51] xe2_04-07-23_16_43_08.txt
INFO 2023-07-04 16:43:08,891 [main.py:captureConfigX:51] xe3_04-07-23_16_43_08.txt
ERROR 2023-07-04 16:43:17,398 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:43:17,516 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:43:38,314 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:43:38,316 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:44:05,735 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:44:05,840 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:44:05,948 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:44:06,057 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:44:06,161 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:44:06,267 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:44:08,086 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:44:08,152 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:44:08,313 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:44:08,604 [main.py:captureConfigX:51] xe1_04-07-23_16_44_08.txt
INFO 2023-07-04 16:44:08,685 [main.py:captureConfigX:51] xe2_04-07-23_16_44_08.txt
INFO 2023-07-04 16:44:08,887 [main.py:captureConfigX:51] xe3_04-07-23_16_44_08.txt
ERROR 2023-07-04 16:44:17,404 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:44:17,538 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-07-04 16:44:23,963 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:44:24,079 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:44:24,182 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:44:24,289 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:44:24,393 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:44:24,503 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:44:26,536 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:44:26,620 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:44:26,641 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:44:27,112 [main.py:captureConfigX:51] xe3_04-07-23_16_44_26.txt
INFO 2023-07-04 16:44:27,144 [main.py:captureConfigX:51] xe2_04-07-23_16_44_26.txt
INFO 2023-07-04 16:44:27,248 [main.py:captureConfigX:51] xe1_04-07-23_16_44_26.txt
ERROR 2023-07-04 16:44:35,751 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:44:35,853 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:44:38,368 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:44:38,370 [main.py:captureConfig:77] Get Config -  execution completed successfully.
ERROR 2023-07-04 16:44:56,688 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:44:56,690 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:45:01,743 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:45:01,849 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:45:01,954 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:45:02,061 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:45:02,167 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:45:02,271 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:45:04,053 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:45:04,144 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:45:04,221 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:45:04,720 [main.py:captureConfigX:51] xe3_04-07-23_16_45_04.txt
INFO 2023-07-04 16:45:04,759 [main.py:captureConfigX:51] xe2_04-07-23_16_45_04.txt
INFO 2023-07-04 16:45:04,782 [main.py:captureConfigX:51] xe1_04-07-23_16_45_04.txt
ERROR 2023-07-04 16:45:13,388 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:45:13,588 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:45:34,348 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:45:34,350 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:47:46,072 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:47:46,177 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:47:46,281 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:47:46,387 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:47:46,492 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:47:46,601 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:47:48,627 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:47:48,857 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:47:48,901 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:47:49,207 [main.py:captureConfigX:51] xe1_04-07-23_16_47_48.txt
INFO 2023-07-04 16:47:49,412 [main.py:captureConfigX:51] xe3_04-07-23_16_47_48.txt
INFO 2023-07-04 16:47:49,492 [main.py:captureConfigX:51] xe2_04-07-23_16_47_48.txt
ERROR 2023-07-04 16:47:57,884 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:47:57,929 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-07-04 16:48:01,790 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:48:01,899 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:48:02,008 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:48:02,115 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:48:02,218 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:48:02,324 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:48:04,373 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:48:04,470 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:48:04,474 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:48:04,975 [main.py:captureConfigX:51] xe2_04-07-23_16_48_04.txt
INFO 2023-07-04 16:48:04,982 [main.py:captureConfigX:51] xe3_04-07-23_16_48_04.txt
INFO 2023-07-04 16:48:05,245 [main.py:captureConfigX:51] xe1_04-07-23_16_48_04.txt
ERROR 2023-07-04 16:48:13,507 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:48:13,618 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:48:18,701 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:48:18,704 [main.py:captureConfig:77] Get Config -  execution completed successfully.
ERROR 2023-07-04 16:48:34,428 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:48:34,434 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:48:48,157 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:48:48,261 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:48:48,367 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:48:48,471 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:48:48,578 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:48:48,685 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:48:50,490 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:48:50,521 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:48:50,711 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:48:51,054 [main.py:captureConfigX:51] xe2_04-07-23_16_48_50.txt
INFO 2023-07-04 16:48:51,109 [main.py:captureConfigX:51] xe1_04-07-23_16_48_50.txt
INFO 2023-07-04 16:48:51,249 [main.py:captureConfigX:51] xe3_04-07-23_16_48_50.txt
ERROR 2023-07-04 16:48:59,788 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:48:59,944 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:20,770 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:49:20,774 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 16:49:21,008 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:49:21,111 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:49:21,214 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:49:21,319 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:49:21,479 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:49:21,590 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:49:21,599 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:49:21,705 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:49:21,758 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 16:49:21,811 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:49:21,867 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 16:49:21,915 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:49:21,973 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 16:49:22,021 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:49:22,079 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 16:49:22,127 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:49:22,183 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 16:49:22,289 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 16:49:23,794 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:49:23,814 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:49:23,839 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:49:24,231 [main.py:captureConfigX:51] xe3_04-07-23_16_49_23.txt
INFO 2023-07-04 16:49:24,272 [main.py:captureConfigX:51] xe2_04-07-23_16_49_23.txt
INFO 2023-07-04 16:49:24,382 [main.py:captureConfigX:51] xe1_04-07-23_16_49_23.txt
INFO 2023-07-04 16:49:24,466 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:49:24,512 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:49:24,514 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 16:49:24,542 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 16:49:24,675 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:49:24,715 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 16:49:24,896 [main.py:captureConfigX:51] xe3_04-07-23_16_49_24.txt
INFO 2023-07-04 16:49:24,955 [main.py:captureConfigX:51] xe2_04-07-23_16_49_24.txt
INFO 2023-07-04 16:49:25,095 [main.py:captureConfigX:51] xe3_04-07-23_16_49_24.txt
INFO 2023-07-04 16:49:25,159 [main.py:captureConfigX:51] xe2_04-07-23_16_49_24.txt
INFO 2023-07-04 16:49:25,225 [main.py:captureConfigX:51] xe1_04-07-23_16_49_24.txt
INFO 2023-07-04 16:49:25,526 [main.py:captureConfigX:51] xe1_04-07-23_16_49_24.txt
ERROR 2023-07-04 16:49:32,740 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:32,878 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:33,020 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:33,130 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:33,181 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:33,292 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 16:49:53,748 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:49:53,750 [main.py:captureConfig:77] Get Config -  execution completed successfully.
ERROR 2023-07-04 16:49:54,248 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:49:54,252 [main.py:captureConfig:77] Get Config -  execution completed successfully.
ERROR 2023-07-04 16:49:54,379 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 16:49:54,380 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 17:11:12,608 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 17:11:12,715 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 17:11:12,820 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 17:11:12,924 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 17:11:13,029 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 17:11:13,138 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 17:11:15,098 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 17:11:15,100 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 17:11:15,247 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 17:11:15,616 [main.py:captureConfigX:51] xe2_04-07-23_17_11_15.txt
INFO 2023-07-04 17:11:15,709 [main.py:captureConfigX:51] xe1_04-07-23_17_11_15.txt
INFO 2023-07-04 17:11:15,807 [main.py:captureConfigX:51] xe3_04-07-23_17_11_15.txt
ERROR 2023-07-04 17:11:24,278 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 17:11:24,400 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 17:11:45,242 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 17:11:45,257 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 17:19:23,742 [main.py:captureConfig:69] Connecting to device xe1
INFO 2023-07-04 17:19:23,849 [main.py:captureConfig:69] Connecting to device xe2
INFO 2023-07-04 17:19:23,953 [main.py:captureConfig:69] Connecting to device xe3
INFO 2023-07-04 17:19:24,058 [main.py:captureConfig:69] Connecting to device xr1
INFO 2023-07-04 17:19:24,164 [main.py:captureConfig:69] Connecting to device xr2
INFO 2023-07-04 17:19:24,268 [main.py:captureConfig:69] Connecting to device xr3
INFO 2023-07-04 17:19:26,218 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 17:19:26,306 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 17:19:26,345 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 17:19:26,779 [main.py:captureConfigX:51] xe1_04-07-23_17_19_26.txt
INFO 2023-07-04 17:19:26,812 [main.py:captureConfigX:51] xe2_04-07-23_17_19_26.txt
INFO 2023-07-04 17:19:26,868 [main.py:captureConfigX:51] xe3_04-07-23_17_19_26.txt
ERROR 2023-07-04 17:19:35,468 [main.py:captureConfigX:60] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 17:19:35,531 [main.py:captureConfigX:60] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 17:19:56,378 [main.py:captureConfigX:60] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 17:19:56,382 [main.py:captureConfig:78] Get Config -  execution completed successfully.
INFO 2023-07-04 18:14:23,686 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:14:23,794 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:14:23,900 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:14:24,004 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:14:24,110 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:14:24,214 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:14:26,235 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:14:26,245 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:14:26,266 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:14:26,753 [main.py:captureConfigX:51] xe3_04-07-23_18_14_26.txt
INFO 2023-07-04 18:14:26,790 [main.py:captureConfigX:51] xe2_04-07-23_18_14_26.txt
INFO 2023-07-04 18:14:26,791 [main.py:captureConfigX:51] xe1_04-07-23_18_14_26.txt
ERROR 2023-07-04 18:14:35,457 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:14:35,459 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:14:56,286 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:14:56,288 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 18:16:05,695 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:16:05,814 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:16:05,937 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:16:06,061 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:16:06,169 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:16:06,275 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:16:08,334 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:16:08,342 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:16:08,379 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:16:08,825 [main.py:captureConfigX:51] xe3_04-07-23_18_16_08.txt
INFO 2023-07-04 18:16:08,831 [main.py:captureConfigX:51] xe2_04-07-23_18_16_08.txt
INFO 2023-07-04 18:16:08,907 [main.py:captureConfigX:51] xe1_04-07-23_18_16_08.txt
ERROR 2023-07-04 18:16:17,554 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:16:17,562 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:16:38,387 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:16:38,389 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 18:17:38,970 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:17:39,074 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:17:39,178 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:17:39,283 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:17:39,388 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:17:39,495 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:17:41,451 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:17:41,476 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:17:41,500 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:17:42,011 [main.py:captureConfigX:51] xe3_04-07-23_18_17_41.txt
INFO 2023-07-04 18:17:42,012 [main.py:captureConfigX:51] xe2_04-07-23_18_17_41.txt
INFO 2023-07-04 18:17:42,078 [main.py:captureConfigX:51] xe1_04-07-23_18_17_41.txt
ERROR 2023-07-04 18:17:50,615 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:17:50,737 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:18:11,601 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:18:11,603 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 18:22:00,771 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:22:00,885 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:22:00,990 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:22:01,094 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:22:01,203 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:22:01,313 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:22:03,264 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:22:03,403 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:22:03,434 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:22:03,838 [main.py:captureConfigX:51] xe1_04-07-23_18_22_03.txt
INFO 2023-07-04 18:22:03,988 [main.py:captureConfigX:51] xe2_04-07-23_18_22_03.txt
INFO 2023-07-04 18:22:04,015 [main.py:captureConfigX:51] xe3_04-07-23_18_22_03.txt
ERROR 2023-07-04 18:22:12,508 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:22:12,559 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:22:33,408 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:22:33,411 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 18:23:10,098 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:23:10,203 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:23:10,306 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:23:10,411 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:23:10,515 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:23:10,620 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:23:12,495 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:23:12,544 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:23:12,611 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:23:13,057 [main.py:captureConfigX:51] xe2_04-07-23_18_23_12.txt
INFO 2023-07-04 18:23:13,107 [main.py:captureConfigX:51] xe3_04-07-23_18_23_12.txt
INFO 2023-07-04 18:23:13,130 [main.py:captureConfigX:51] xe1_04-07-23_18_23_12.txt
ERROR 2023-07-04 18:23:21,799 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:23:21,958 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:23:42,705 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:23:42,707 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 18:24:31,288 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:24:31,392 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:24:31,497 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:24:31,603 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:24:31,707 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:24:31,812 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:24:33,654 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:24:33,712 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:24:33,917 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:24:34,215 [main.py:captureConfigX:51] xe2_04-07-23_18_24_33.txt
INFO 2023-07-04 18:24:34,243 [main.py:captureConfigX:51] xe1_04-07-23_18_24_33.txt
INFO 2023-07-04 18:24:34,454 [main.py:captureConfigX:51] xe3_04-07-23_18_24_33.txt
ERROR 2023-07-04 18:24:42,931 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:24:43,070 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:25:03,919 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:25:03,923 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-04 18:25:23,326 [main.py:captureConfig:68] Connecting to device xe1
INFO 2023-07-04 18:25:23,443 [main.py:captureConfig:68] Connecting to device xe2
INFO 2023-07-04 18:25:23,554 [main.py:captureConfig:68] Connecting to device xe3
INFO 2023-07-04 18:25:23,701 [main.py:captureConfig:68] Connecting to device xr1
INFO 2023-07-04 18:25:23,827 [main.py:captureConfig:68] Connecting to device xr2
INFO 2023-07-04 18:25:23,939 [main.py:captureConfig:68] Connecting to device xr3
INFO 2023-07-04 18:25:25,937 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-04 18:25:26,059 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-04 18:25:26,072 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-04 18:25:26,421 [main.py:captureConfigX:51] xe3_04-07-23_18_25_25.txt
INFO 2023-07-04 18:25:26,562 [main.py:captureConfigX:51] xe2_04-07-23_18_25_26.txt
INFO 2023-07-04 18:25:26,618 [main.py:captureConfigX:51] xe1_04-07-23_18_25_26.txt
ERROR 2023-07-04 18:25:35,098 [main.py:captureConfigX:59] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state
ERROR 2023-07-04 18:25:35,231 [main.py:captureConfigX:59] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state
ERROR 2023-07-04 18:25:56,055 [main.py:captureConfigX:59] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-07-04 18:25:56,057 [main.py:captureConfig:77] Get Config -  execution completed successfully.
INFO 2023-07-05 09:54:51,368 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 09:54:51,989 [main.py:captureConfigX:51] xe1_05-07-23_09_54_51.txt
INFO 2023-07-05 09:56:03,411 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 09:56:03,433 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 09:56:03,582 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 09:56:03,966 [main.py:captureConfigX:51] xe2_05-07-23_09_56_03.txt
INFO 2023-07-05 09:56:03,978 [main.py:captureConfigX:51] xe1_05-07-23_09_56_03.txt
INFO 2023-07-05 09:56:04,120 [main.py:captureConfigX:51] xe3_05-07-23_09_56_03.txt
INFO 2023-07-05 09:56:13,071 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 09:56:13,143 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 09:56:13,325 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 09:56:13,620 [main.py:captureConfigX:51] xe1_05-07-23_09_56_13.txt
INFO 2023-07-05 09:56:13,620 [main.py:captureConfigX:51] xe2_05-07-23_09_56_13.txt
INFO 2023-07-05 09:56:13,799 [main.py:captureConfigX:51] xe3_05-07-23_09_56_13.txt
INFO 2023-07-05 10:04:04,107 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:04:04,194 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:04:04,517 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:04:04,685 [main.py:captureConfigX:51] xe2_05-07-23_10_04_04.txt
INFO 2023-07-05 10:04:04,737 [main.py:captureConfigX:51] xe1_05-07-23_10_04_04.txt
INFO 2023-07-05 10:04:05,011 [main.py:captureConfigX:51] xe3_05-07-23_10_04_04.txt
INFO 2023-07-05 10:04:26,092 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:04:26,280 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:04:26,325 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:04:26,657 [main.py:captureConfigX:51] xe1_05-07-23_10_04_26.txt
INFO 2023-07-05 10:04:26,766 [main.py:captureConfigX:51] xe2_05-07-23_10_04_26.txt
INFO 2023-07-05 10:04:26,810 [main.py:captureConfigX:51] xe3_05-07-23_10_04_26.txt
INFO 2023-07-05 10:04:34,658 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:04:34,878 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:04:34,955 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:04:35,233 [main.py:captureConfigX:51] xe1_05-07-23_10_04_34.txt
INFO 2023-07-05 10:04:35,399 [main.py:captureConfigX:51] xe2_05-07-23_10_04_34.txt
INFO 2023-07-05 10:04:35,535 [main.py:captureConfigX:51] xe3_05-07-23_10_04_34.txt
INFO 2023-07-05 10:05:29,202 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:05:29,335 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:05:29,425 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:05:29,766 [main.py:captureConfigX:51] xe1_05-07-23_10_05_29.txt
INFO 2023-07-05 10:05:29,854 [main.py:captureConfigX:51] xe2_05-07-23_10_05_29.txt
INFO 2023-07-05 10:05:29,922 [main.py:captureConfigX:51] xe3_05-07-23_10_05_29.txt
INFO 2023-07-05 10:05:40,545 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:05:40,632 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:05:40,779 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:05:41,103 [main.py:captureConfigX:51] xe1_05-07-23_10_05_40.txt
INFO 2023-07-05 10:05:41,109 [main.py:captureConfigX:51] xe2_05-07-23_10_05_40.txt
INFO 2023-07-05 10:05:41,265 [main.py:captureConfigX:51] xe3_05-07-23_10_05_40.txt
INFO 2023-07-05 10:08:06,720 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:08:06,943 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:08:06,960 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:08:07,286 [main.py:captureConfigX:51] xe1_05-07-23_10_08_06.txt
INFO 2023-07-05 10:08:07,506 [main.py:captureConfigX:51] xe3_05-07-23_10_08_06.txt
INFO 2023-07-05 10:08:07,511 [main.py:captureConfigX:51] xe2_05-07-23_10_08_06.txt
INFO 2023-07-05 10:09:55,060 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:09:55,082 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:09:55,123 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:09:55,577 [main.py:captureConfigX:51] xe2_05-07-23_10_09_55.txt
INFO 2023-07-05 10:09:55,635 [main.py:captureConfigX:51] xe3_05-07-23_10_09_55.txt
INFO 2023-07-05 10:09:55,673 [main.py:captureConfigX:51] xe1_05-07-23_10_09_55.txt
INFO 2023-07-05 10:42:08,883 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:42:09,072 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:42:09,132 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:42:09,519 [main.py:captureConfigX:51] xe1_05-07-23_10_42_08.txt
INFO 2023-07-05 10:42:09,584 [main.py:captureConfigX:51] xe3_05-07-23_10_42_09.txt
INFO 2023-07-05 10:42:09,674 [main.py:captureConfigX:51] xe2_05-07-23_10_42_09.txt
INFO 2023-07-05 10:42:17,319 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:42:17,339 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:42:17,356 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:42:17,836 [main.py:captureConfigX:51] xe3_05-07-23_10_42_17.txt
INFO 2023-07-05 10:42:17,857 [main.py:captureConfigX:51] xe2_05-07-23_10_42_17.txt
INFO 2023-07-05 10:42:18,019 [main.py:captureConfigX:51] xe1_05-07-23_10_42_17.txt
INFO 2023-07-05 10:49:32,633 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:49:33,029 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:49:33,030 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:49:33,261 [main.py:captureConfigX:51] xe1_05-07-23_10_49_32.txt
INFO 2023-07-05 10:49:33,488 [main.py:captureConfigX:51] xe3_05-07-23_10_49_33.txt
INFO 2023-07-05 10:49:33,511 [main.py:captureConfigX:51] xe2_05-07-23_10_49_33.txt
INFO 2023-07-05 10:50:10,494 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:50:10,605 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:50:10,672 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:50:11,085 [main.py:captureConfigX:51] xe1_05-07-23_10_50_10.txt
INFO 2023-07-05 10:50:11,180 [main.py:captureConfigX:51] xe3_05-07-23_10_50_10.txt
INFO 2023-07-05 10:50:11,213 [main.py:captureConfigX:51] xe2_05-07-23_10_50_10.txt
INFO 2023-07-05 10:52:08,478 [main.py:captureConfigX:45] ---getting capture config from device xe1---
INFO 2023-07-05 10:52:08,492 [main.py:captureConfigX:45] ---getting capture config from device xe2---
INFO 2023-07-05 10:52:08,561 [main.py:captureConfigX:45] ---getting capture config from device xe3---
INFO 2023-07-05 10:52:09,005 [main.py:captureConfigX:51] xe2_05-07-23_10_52_08.txt
INFO 2023-07-05 10:52:09,047 [main.py:captureConfigX:51] xe1_05-07-23_10_52_08.txt
INFO 2023-07-05 10:52:09,060 [main.py:captureConfigX:51] xe3_05-07-23_10_52_08.txt
INFO 2023-07-05 11:13:23,032 [main.py:captureConfigX:51] xe1_05-07-23_11_13_22.txt
INFO 2023-07-05 11:13:23,083 [main.py:captureConfigX:51] xe2_05-07-23_11_13_22.txt
INFO 2023-07-05 11:13:23,214 [main.py:captureConfigX:51] xe3_05-07-23_11_13_22.txt
