INFO 2023-08-15 20:47:58,461 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 20:47:58,464 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 20:47:58,565 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 20:47:58,569 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 20:47:58,666 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 20:47:58,669 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 20:48:01,565 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:48:01,568 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-15 20:48:01,611 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:48:01,623 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-15 20:48:01,698 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:48:01,702 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-15 20:48:03,574 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 20:48:03,629 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 20:48:03,707 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 20:48:06,602 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:48:06,607 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-15 20:48:06,658 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:48:06,663 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-15 20:48:06,738 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:48:06,742 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-15 20:48:08,612 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 20:48:08,669 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 20:48:08,747 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 20:48:11,646 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:48:11,649 [main.py:get_iosxe_memory_info:142] Maximum retries reached. Unable to establish connection to device 198.18.0.121.
ERROR 2023-08-15 20:48:11,700 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:48:11,703 [main.py:get_iosxe_memory_info:142] Maximum retries reached. Unable to establish connection to device 198.18.0.122.
ERROR 2023-08-15 20:48:11,779 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:48:11,782 [main.py:get_iosxe_memory_info:142] Maximum retries reached. Unable to establish connection to device 198.18.0.123.
INFO 2023-08-15 20:48:11,785 [main.py:getMemmoryUtils:426] Get Memmory Utilization - execution completed.
INFO 2023-08-15 20:48:11,787 [main.py:getMemmoryUtils:429] Sort Output Data - execution completed.
INFO 2023-08-15 20:49:49,559 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 20:49:49,666 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 20:49:49,772 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
ERROR 2023-08-15 20:50:03,652 [main.py:get_iosxe_memory_info:92] Connection attempt 1/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-15 20:50:03,658 [main.py:get_iosxe_memory_info:93] Retrying in 2 seconds...
ERROR 2023-08-15 20:50:03,761 [main.py:get_iosxe_memory_info:92] Connection attempt 1/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-15 20:50:03,763 [main.py:get_iosxe_memory_info:93] Retrying in 2 seconds...
ERROR 2023-08-15 20:50:03,904 [main.py:get_iosxe_memory_info:92] Connection attempt 1/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-15 20:50:03,907 [main.py:get_iosxe_memory_info:93] Retrying in 2 seconds...
INFO 2023-08-15 20:50:05,663 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 2
INFO 2023-08-15 20:50:05,771 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 2
INFO 2023-08-15 20:50:05,912 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 2
ERROR 2023-08-15 20:50:19,841 [main.py:get_iosxe_memory_info:92] Connection attempt 2/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-15 20:50:19,846 [main.py:get_iosxe_memory_info:93] Retrying in 2 seconds...
ERROR 2023-08-15 20:50:19,855 [main.py:get_iosxe_memory_info:92] Connection attempt 2/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-15 20:50:19,859 [main.py:get_iosxe_memory_info:93] Retrying in 2 seconds...
ERROR 2023-08-15 20:50:20,047 [main.py:get_iosxe_memory_info:92] Connection attempt 2/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-15 20:50:20,049 [main.py:get_iosxe_memory_info:93] Retrying in 2 seconds...
INFO 2023-08-15 20:50:21,851 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 3
INFO 2023-08-15 20:50:21,864 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 3
INFO 2023-08-15 20:50:22,052 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 3
ERROR 2023-08-15 20:50:36,016 [main.py:get_iosxe_memory_info:96] Failed to establish connection to xe2 (198.18.0.122) after 3 attempts.
ERROR 2023-08-15 20:50:36,027 [main.py:get_iosxe_memory_info:96] Failed to establish connection to xe1 (198.18.0.121) after 3 attempts.
INFO 2023-08-15 20:50:36,032 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 20:50:36,039 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 20:50:36,047 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 20:50:36,055 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-15 20:50:36,228 [main.py:get_iosxe_memory_info:96] Failed to establish connection to xe3 (198.18.0.123) after 3 attempts.
INFO 2023-08-15 20:50:36,232 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 20:50:36,235 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 20:50:39,129 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:50:39,141 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:50:39,149 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.122 in 2 seconds...
INFO 2023-08-15 20:50:39,149 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-15 20:50:39,279 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:50:39,283 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-15 20:50:41,158 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 20:50:41,162 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 20:50:41,287 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 20:50:44,257 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:50:44,263 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:50:44,270 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.122 in 2 seconds...
INFO 2023-08-15 20:50:44,275 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-15 20:50:44,324 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-15 20:50:44,327 [main.py:get_iosxe_memory_info:139] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-15 20:50:46,281 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 20:50:46,284 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 20:50:46,331 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 20:50:49,320 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:50:49,329 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:50:49,335 [main.py:get_iosxe_memory_info:142] Maximum retries reached. Unable to establish connection to device 198.18.0.122.
ERROR 2023-08-15 20:50:49,341 [main.py:get_iosxe_memory_info:142] Maximum retries reached. Unable to establish connection to device 198.18.0.121.
ERROR 2023-08-15 20:50:49,372 [main.py:get_iosxe_memory_info:136] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-15 20:50:49,379 [main.py:get_iosxe_memory_info:142] Maximum retries reached. Unable to establish connection to device 198.18.0.123.
INFO 2023-08-15 20:50:49,383 [main.py:getMemmoryUtils:426] Get Memmory Utilization - execution completed.
INFO 2023-08-15 20:50:49,390 [main.py:getMemmoryUtils:429] Sort Output Data - execution completed.
INFO 2023-08-15 20:53:21,205 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 20:53:21,311 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 20:53:21,417 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 20:53:25,147 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 20:53:25,176 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 20:53:25,373 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 20:53:39,663 [main.py:get_iosxe_memory_info:84] Parse Device: xe2 Data Successfully
INFO 2023-08-15 20:53:39,934 [main.py:get_iosxe_memory_info:84] Parse Device: xe3 Data Successfully
INFO 2023-08-15 20:53:40,712 [main.py:get_iosxe_memory_info:84] Parse Device: xe1 Data Successfully
INFO 2023-08-15 20:53:40,715 [main.py:getMemmoryUtils:426] Get Memmory Utilization - execution completed.
INFO 2023-08-15 20:53:40,719 [main.py:getMemmoryUtils:429] Sort Output Data - execution completed.
INFO 2023-08-15 21:10:38,091 [main.py:get_ios_memory_info:233] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 21:10:38,196 [main.py:get_ios_memory_info:233] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 21:10:38,307 [main.py:get_ios_memory_info:233] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 21:10:39,038 [main.py:get_ios_memory_info:236] Device: xe1 Connected Successfully
INFO 2023-08-15 21:10:41,776 [main.py:get_ios_memory_info:236] Device: xe3 Connected Successfully
INFO 2023-08-15 21:10:44,711 [main.py:get_ios_memory_info:236] Device: xe2 Connected Successfully
INFO 2023-08-15 21:11:02,621 [main.py:get_ios_memory_info:240] Parse Device: xe3 Data Successfully
INFO 2023-08-15 21:11:06,434 [main.py:get_ios_memory_info:240] Parse Device: xe1 Data Successfully
INFO 2023-08-15 21:11:07,950 [main.py:get_ios_memory_info:240] Parse Device: xe2 Data Successfully
INFO 2023-08-15 21:11:07,954 [main.py:getMemmoryUtils:428] Get Memmory Utilization - execution completed.
INFO 2023-08-15 21:11:07,960 [main.py:getMemmoryUtils:431] Sort Output Data - execution completed.
INFO 2023-08-15 21:49:54,117 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 21:49:54,221 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 21:49:54,332 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 21:49:56,105 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 21:49:56,395 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 21:49:56,415 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 21:50:02,271 [main.py:get_iosxe_memory_info:84] Parse Device: xe1 Data Successfully
INFO 2023-08-15 21:50:02,276 [main.py:get_iosxe_memory_info:122] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 21:50:02,280 [main.py:get_iosxe_memory_info:133] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 21:50:05,280 [main.py:get_iosxe_memory_info:84] Parse Device: xe2 Data Successfully
INFO 2023-08-15 21:50:05,284 [main.py:get_iosxe_memory_info:122] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 21:50:05,287 [main.py:get_iosxe_memory_info:133] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 21:50:08,426 [main.py:get_iosxe_memory_info:84] Parse Device: xe3 Data Successfully
INFO 2023-08-15 21:50:08,429 [main.py:get_iosxe_memory_info:122] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 21:50:08,432 [main.py:get_iosxe_memory_info:133] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-15 21:50:12,344 [main.py:getMemmoryUtils:455] Get Memmory Utilization - execution completed.
INFO 2023-08-15 21:50:12,349 [main.py:getMemmoryUtils:458] Sort Output Data - execution completed.
INFO 2023-08-15 21:52:04,463 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 21:52:04,569 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 21:52:04,676 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 21:52:05,401 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 21:52:08,482 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 21:52:14,598 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 21:52:17,929 [main.py:get_iosxe_memory_info:84] Parse Device: xe1 Data Successfully
INFO 2023-08-15 21:52:17,939 [main.py:get_iosxe_memory_info:122] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 21:52:17,954 [main.py:get_iosxe_memory_info:133] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 21:52:18,027 [main.py:get_iosxe_memory_info:84] Parse Device: xe3 Data Successfully
INFO 2023-08-15 21:52:18,032 [main.py:get_iosxe_memory_info:122] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 21:52:18,038 [main.py:get_iosxe_memory_info:133] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-15 21:52:26,608 [main.py:get_iosxe_memory_info:84] Parse Device: xe2 Data Successfully
INFO 2023-08-15 21:52:26,611 [main.py:get_iosxe_memory_info:122] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 21:52:26,614 [main.py:get_iosxe_memory_info:133] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 21:52:28,049 [main.py:getMemmoryUtils:455] Get Memmory Utilization - execution completed.
INFO 2023-08-15 21:52:28,054 [main.py:getMemmoryUtils:458] Sort Output Data - execution completed.
INFO 2023-08-15 21:55:16,742 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 21:55:16,847 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 21:55:16,949 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 21:55:17,598 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 21:55:19,671 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 21:55:20,713 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 21:55:28,916 [main.py:get_iosxe_memory_info:84] Parse Device: xe3 Data Successfully
INFO 2023-08-15 21:55:28,919 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 21:55:28,922 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-15 21:55:31,299 [main.py:get_iosxe_memory_info:84] Parse Device: xe1 Data Successfully
INFO 2023-08-15 21:55:31,302 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 21:55:31,305 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 21:55:31,482 [main.py:get_iosxe_memory_info:84] Parse Device: xe2 Data Successfully
INFO 2023-08-15 21:55:31,484 [main.py:get_iosxe_memory_info:121] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 21:55:31,487 [main.py:get_iosxe_memory_info:132] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 21:55:32,961 [main.py:getMemmoryUtils:454] Get Memmory Utilization - execution completed.
INFO 2023-08-15 21:55:32,965 [main.py:getMemmoryUtils:457] Sort Output Data - execution completed.
INFO 2023-08-15 21:57:16,737 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 21:57:16,844 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 21:57:16,953 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 21:57:17,776 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 21:57:22,799 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 21:57:23,949 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 21:57:26,774 [main.py:get_iosxe_memory_info:95] Parse Device: xe2 Data Successfully
INFO 2023-08-15 21:57:26,778 [main.py:get_iosxe_memory_info:120] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 21:57:26,782 [main.py:get_iosxe_memory_info:131] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 21:57:26,933 [main.py:get_iosxe_memory_info:95] Parse Device: xe1 Data Successfully
INFO 2023-08-15 21:57:26,937 [main.py:get_iosxe_memory_info:120] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 21:57:26,943 [main.py:get_iosxe_memory_info:131] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 21:57:30,252 [main.py:get_iosxe_memory_info:95] Parse Device: xe3 Data Successfully
INFO 2023-08-15 21:57:30,254 [main.py:get_iosxe_memory_info:120] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 21:57:30,257 [main.py:get_iosxe_memory_info:131] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-15 21:57:36,909 [main.py:get_iosxe_memory_info:135] Authentication or connection error (attempt 1/3) for device 198.18.0.122: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 15 seconds or larger.
INFO 2023-08-15 21:57:36,914 [main.py:get_iosxe_memory_info:138] Retrying 198.18.0.122 in 2 seconds...
INFO 2023-08-15 21:57:38,920 [main.py:get_iosxe_memory_info:131] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 21:57:43,072 [main.py:getMemmoryUtils:453] Get Memmory Utilization - execution completed.
INFO 2023-08-15 21:57:43,075 [main.py:getMemmoryUtils:456] Sort Output Data - execution completed.
INFO 2023-08-15 22:01:41,856 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:01:41,963 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:01:42,071 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:01:42,705 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 22:01:45,738 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 22:01:45,894 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 22:01:53,639 [main.py:get_iosxe_memory_info:95] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:01:56,085 [main.py:get_iosxe_memory_info:95] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:01:56,713 [main.py:get_iosxe_memory_info:95] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:01:56,717 [main.py:getMemmoryUtils:453] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:01:56,723 [main.py:getMemmoryUtils:456] Sort Output Data - execution completed.
INFO 2023-08-15 22:09:51,527 [main.py:get_iosxe_memory_info:81] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:09:55,385 [main.py:get_iosxe_memory_info:84] Device: xe1 Connected Successfully
INFO 2023-08-15 22:10:00,933 [main.py:get_iosxe_memory_info:99] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:11:04,152 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:11:04,256 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:11:04,368 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:11:05,038 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:11:05,105 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:11:05,230 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:11:09,298 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:11:10,762 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:11:12,756 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:11:12,759 [main.py:getMemmoryUtils:454] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:11:12,763 [main.py:getMemmoryUtils:457] Sort Output Data - execution completed.
INFO 2023-08-15 22:14:49,501 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:14:49,605 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:14:49,712 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:14:50,412 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:14:50,438 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:14:52,991 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:14:57,728 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:14:57,733 [main.py:get_iosxe_memory_info:124] Failed to Connect Using Main Function pyats iosxe for xe1
INFO 2023-08-15 22:14:57,739 [main.py:get_iosxe_memory_info:135] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-15 22:14:58,723 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:14:58,735 [main.py:get_iosxe_memory_info:124] Failed to Connect Using Main Function pyats iosxe for xe2
INFO 2023-08-15 22:14:58,740 [main.py:get_iosxe_memory_info:135] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-15 22:15:02,964 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:15:02,968 [main.py:get_iosxe_memory_info:124] Failed to Connect Using Main Function pyats iosxe for xe3
INFO 2023-08-15 22:15:02,971 [main.py:get_iosxe_memory_info:135] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-15 22:15:06,882 [main.py:getMemmoryUtils:451] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:15:06,887 [main.py:getMemmoryUtils:454] Sort Output Data - execution completed.
INFO 2023-08-15 22:15:28,282 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:15:28,388 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:15:28,490 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:15:29,220 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:15:29,347 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:15:29,454 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:15:33,714 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:15:34,440 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:15:36,787 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:15:36,792 [main.py:getMemmoryUtils:451] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:15:36,798 [main.py:getMemmoryUtils:454] Sort Output Data - execution completed.
INFO 2023-08-15 22:21:57,357 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:21:57,463 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:21:57,570 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:21:58,206 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:21:58,305 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:21:58,415 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:22:05,882 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:22:06,782 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:22:09,527 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:22:09,531 [main.py:getMemmoryUtils:449] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:22:09,538 [main.py:getMemmoryUtils:452] Sort Output Data - execution completed.
INFO 2023-08-15 22:24:57,839 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:24:57,943 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:24:58,049 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:24:58,734 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:25:02,005 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:25:02,200 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:25:06,118 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:25:07,745 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:25:09,866 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:25:09,871 [main.py:getMemmoryUtils:450] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:25:09,878 [main.py:getMemmoryUtils:453] Sort Output Data - execution completed.
INFO 2023-08-15 22:27:02,673 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:27:02,777 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:27:02,883 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:27:03,503 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:27:03,670 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:27:05,655 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:27:09,130 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:27:10,733 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:27:14,752 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:27:14,757 [main.py:getMemmoryUtils:450] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:27:14,761 [main.py:getMemmoryUtils:453] Sort Output Data - execution completed.
INFO 2023-08-15 22:39:48,039 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:39:48,148 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:39:48,256 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:39:48,879 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:39:49,131 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:39:51,813 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:39:52,126 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:39:53,451 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:39:56,252 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:39:56,257 [main.py:getMemmoryUtils:454] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:39:56,262 [main.py:getMemmoryUtils:457] Sort Output Data - execution completed.
INFO 2023-08-15 22:39:56,267 [main.py:getMemmoryUtils:458] Total Executed Device is IOS_XE:3 IOS_XR:0 IOS:0 NXOS:0 and Total Device is 0
INFO 2023-08-15 22:42:54,148 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:42:54,253 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:42:54,362 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:42:54,997 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:42:55,157 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:42:55,202 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:42:58,577 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:42:59,767 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:43:00,659 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:43:00,661 [main.py:getMemmoryUtils:457] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:43:00,663 [main.py:getMemmoryUtils:460] Sort Output Data - execution completed.
INFO 2023-08-15 22:43:00,665 [main.py:getMemmoryUtils:461] Total Executed Device is IOS_XE:3 IOS_XR:0 IOS:0 NXOS:0 and Total Device is 3
INFO 2023-08-15 22:44:25,329 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:44:25,432 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:44:25,536 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:44:26,268 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:44:26,275 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:44:26,322 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:44:28,769 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:44:29,075 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:44:31,847 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:44:31,850 [main.py:getMemmoryUtils:456] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:44:31,851 [main.py:getMemmoryUtils:459] Sort Output Data - execution completed.
INFO 2023-08-15 22:44:31,854 [main.py:getMemmoryUtils:460] Total Executed Device is IOS_XE:3 IOS_XR:0 IOS:0 NXOS:0 and Total Device is 3
INFO 2023-08-15 22:46:26,337 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:46:26,439 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:46:26,543 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:46:27,257 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:46:27,366 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:46:27,423 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:46:30,072 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:46:30,814 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:46:30,889 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
ERROR 2023-08-15 22:46:38,375 [main.py:get_iosxr_memory_info:219] Error connecting to device xr1: failed to connect to xr1
Failed while bringing device to "any" state using both fucntion
ERROR 2023-08-15 22:46:38,531 [main.py:get_iosxr_memory_info:219] Error connecting to device xr2: failed to connect to xr2
Failed while bringing device to "any" state using both fucntion
ERROR 2023-08-15 22:46:58,908 [main.py:get_iosxr_memory_info:219] Error connecting to device xr3: failed to connect to xr3
Failed while bringing device to "any" state using both fucntion
INFO 2023-08-15 22:46:58,911 [main.py:getMemmoryUtils:456] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:46:58,914 [main.py:getMemmoryUtils:459] Sort Output Data - execution completed.
INFO 2023-08-15 22:46:58,916 [main.py:getMemmoryUtils:460] Total Executed Device is IOS_XE:3 IOS_XR:3 IOS:0 NXOS:0 and Total Device is 6
INFO 2023-08-15 22:53:04,810 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:53:04,915 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:53:05,018 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:53:05,124 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 1
INFO 2023-08-15 22:53:05,230 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 1
INFO 2023-08-15 22:53:05,335 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 1
INFO 2023-08-15 22:53:05,676 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:53:05,840 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:53:06,039 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:53:10,268 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 22:53:11,830 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:53:12,426 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
ERROR 2023-08-15 22:53:16,754 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 22:53:16,757 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
ERROR 2023-08-15 22:53:17,212 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 22:53:17,215 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:53:18,763 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 2
INFO 2023-08-15 22:53:19,221 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 2
ERROR 2023-08-15 22:53:30,492 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 22:53:30,495 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
ERROR 2023-08-15 22:53:30,950 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 22:53:30,951 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:53:32,500 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 3
INFO 2023-08-15 22:53:32,954 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 3
ERROR 2023-08-15 22:53:37,407 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 22:53:37,409 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:53:39,413 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-15 22:53:44,248 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts.
ERROR 2023-08-15 22:53:44,251 [main.py:get_iosxr_memory_info:237] Error connecting to device xr1: local variable 'output' referenced before assignment using both fucntion
ERROR 2023-08-15 22:53:44,732 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts.
ERROR 2023-08-15 22:53:44,734 [main.py:get_iosxr_memory_info:237] Error connecting to device xr2: local variable 'output' referenced before assignment using both fucntion
ERROR 2023-08-15 22:54:11,459 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 22:54:11,462 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:54:13,466 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-15 22:54:45,529 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr3 (198.18.0.133) after 3 attempts.
ERROR 2023-08-15 22:54:45,531 [main.py:get_iosxr_memory_info:237] Error connecting to device xr3: local variable 'output' referenced before assignment using both fucntion
INFO 2023-08-15 22:54:45,533 [main.py:getMemmoryUtils:474] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:54:45,535 [main.py:getMemmoryUtils:477] Sort Output Data - execution completed.
INFO 2023-08-15 22:54:45,537 [main.py:getMemmoryUtils:478] Total Executed Device is IOS_XE:3 IOS_XR:3 IOS:0 NXOS:0 and Total Device is 6
INFO 2023-08-15 22:56:04,636 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 22:56:04,737 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 22:56:04,840 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 22:56:04,944 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 1
INFO 2023-08-15 22:56:05,048 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 1
INFO 2023-08-15 22:56:05,150 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 1
INFO 2023-08-15 22:56:05,462 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 22:56:05,574 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 22:56:05,806 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 22:56:07,784 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 22:56:08,088 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
INFO 2023-08-15 22:56:08,801 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
ERROR 2023-08-15 22:56:16,641 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 22:56:16,643 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
ERROR 2023-08-15 22:56:16,800 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 22:56:16,803 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:56:18,647 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 2
INFO 2023-08-15 22:56:18,808 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 2
ERROR 2023-08-15 22:56:30,291 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 22:56:30,294 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
ERROR 2023-08-15 22:56:30,539 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 22:56:30,542 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:56:32,298 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 3
INFO 2023-08-15 22:56:32,548 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 3
ERROR 2023-08-15 22:56:37,212 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 22:56:37,215 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:56:39,219 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-15 22:56:43,979 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts.
ERROR 2023-08-15 22:56:43,982 [main.py:get_iosxr_memory_info:237] Error connecting or gather device xr1
ERROR 2023-08-15 22:56:44,261 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts.
ERROR 2023-08-15 22:56:44,263 [main.py:get_iosxr_memory_info:237] Error connecting or gather device xr2
ERROR 2023-08-15 22:57:11,296 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 22:57:11,298 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 22:57:13,302 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-15 22:57:45,377 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr3 (198.18.0.133) after 3 attempts.
ERROR 2023-08-15 22:57:45,380 [main.py:get_iosxr_memory_info:237] Error connecting or gather device xr3
INFO 2023-08-15 22:57:45,382 [main.py:getMemmoryUtils:474] Get Memmory Utilization - execution completed.
INFO 2023-08-15 22:57:45,384 [main.py:getMemmoryUtils:477] Sort Output Data - execution completed.
INFO 2023-08-15 22:57:45,386 [main.py:getMemmoryUtils:478] Total Executed Device is IOS_XE:3 IOS_XR:3 IOS:0 NXOS:0 and Total Device is 6
INFO 2023-08-15 23:12:46,573 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 23:12:46,677 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 23:12:46,782 [main.py:get_iosxe_memory_info:80] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 23:12:46,886 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 1
INFO 2023-08-15 23:12:46,991 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 1
INFO 2023-08-15 23:12:47,094 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 1
INFO 2023-08-15 23:12:47,366 [main.py:get_iosxe_memory_info:83] Device: xe1 Connected Successfully
INFO 2023-08-15 23:12:47,464 [main.py:get_iosxe_memory_info:83] Device: xe2 Connected Successfully
INFO 2023-08-15 23:12:47,567 [main.py:get_iosxe_memory_info:83] Device: xe3 Connected Successfully
INFO 2023-08-15 23:12:49,721 [main.py:get_iosxe_memory_info:98] Parse Device: xe2 Data Successfully
INFO 2023-08-15 23:12:49,748 [main.py:get_iosxe_memory_info:98] Parse Device: xe3 Data Successfully
INFO 2023-08-15 23:12:50,028 [main.py:get_iosxe_memory_info:98] Parse Device: xe1 Data Successfully
ERROR 2023-08-15 23:12:58,535 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 23:12:58,537 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
ERROR 2023-08-15 23:12:58,597 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 23:12:58,599 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 23:13:00,541 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 2
INFO 2023-08-15 23:13:00,600 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 2
ERROR 2023-08-15 23:13:12,213 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 23:13:12,215 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
ERROR 2023-08-15 23:13:12,268 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 23:13:12,270 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 23:13:14,219 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr1 attempt 3
INFO 2023-08-15 23:13:14,272 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr2 attempt 3
ERROR 2023-08-15 23:13:19,149 [main.py:get_iosxr_memory_info:208] Connection attempt 1/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 23:13:19,150 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 23:13:21,155 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-15 23:13:25,891 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts.
ERROR 2023-08-15 23:13:25,893 [main.py:get_iosxr_memory_info:237] Error connecting or gather device xr1
ERROR 2023-08-15 23:13:25,997 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts.
ERROR 2023-08-15 23:13:25,999 [main.py:get_iosxr_memory_info:237] Error connecting or gather device xr2
ERROR 2023-08-15 23:13:53,212 [main.py:get_iosxr_memory_info:208] Connection attempt 2/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 23:13:53,214 [main.py:get_iosxr_memory_info:209] Retrying in 2 seconds...
INFO 2023-08-15 23:13:55,217 [main.py:get_iosxr_memory_info:193] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-15 23:14:27,265 [main.py:get_iosxr_memory_info:212] Failed to establish connection to xr3 (198.18.0.133) after 3 attempts.
ERROR 2023-08-15 23:14:27,268 [main.py:get_iosxr_memory_info:237] Error connecting or gather device xr3
INFO 2023-08-15 23:14:27,269 [main.py:getMemmoryUtils:478] Get Memmory Utilization - execution completed.
INFO 2023-08-15 23:14:27,271 [main.py:getMemmoryUtils:481] Sort Output Data - execution completed.
INFO 2023-08-15 23:14:27,274 [main.py:getMemmoryUtils:482] Total Executed Get Memory Device is IOS_XE:3 IOS_XR:3 IOS:0 NXOS:0 and Total Device is 6
INFO 2023-08-15 23:29:29,927 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe1 attempt 1
INFO 2023-08-15 23:29:30,033 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe2 attempt 1
INFO 2023-08-15 23:29:30,139 [main.py:get_iosxe_memory_info:77] Initiate connection to Device xe3 attempt 1
INFO 2023-08-15 23:29:30,243 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr1 attempt 1
INFO 2023-08-15 23:29:30,347 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr2 attempt 1
INFO 2023-08-15 23:29:30,455 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr3 attempt 1
INFO 2023-08-15 23:29:30,762 [main.py:get_iosxe_memory_info:80] Device: xe1 Connected Successfully
INFO 2023-08-15 23:29:30,867 [main.py:get_iosxe_memory_info:80] Device: xe2 Connected Successfully
INFO 2023-08-15 23:29:30,956 [main.py:get_iosxe_memory_info:80] Device: xe3 Connected Successfully
INFO 2023-08-15 23:29:33,205 [main.py:get_iosxe_memory_info:95] Parse Device: xe2 Data Successfully
INFO 2023-08-15 23:29:33,280 [main.py:get_iosxe_memory_info:95] Parse Device: xe3 Data Successfully
INFO 2023-08-15 23:29:33,420 [main.py:get_iosxe_memory_info:95] Parse Device: xe1 Data Successfully
ERROR 2023-08-15 23:29:41,923 [main.py:get_iosxr_memory_info:205] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 23:29:41,926 [main.py:get_iosxr_memory_info:206] Retrying in 2 seconds...
ERROR 2023-08-15 23:29:42,024 [main.py:get_iosxr_memory_info:205] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 23:29:42,026 [main.py:get_iosxr_memory_info:206] Retrying in 2 seconds...
INFO 2023-08-15 23:29:43,928 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr1 attempt 2
INFO 2023-08-15 23:29:44,028 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr2 attempt 2
ERROR 2023-08-15 23:29:55,654 [main.py:get_iosxr_memory_info:205] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-15 23:29:55,657 [main.py:get_iosxr_memory_info:206] Retrying in 2 seconds...
ERROR 2023-08-15 23:29:55,691 [main.py:get_iosxr_memory_info:205] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-15 23:29:55,694 [main.py:get_iosxr_memory_info:206] Retrying in 2 seconds...
INFO 2023-08-15 23:29:57,662 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr1 attempt 3
INFO 2023-08-15 23:29:57,697 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr2 attempt 3
ERROR 2023-08-15 23:30:02,513 [main.py:get_iosxr_memory_info:205] Connection attempt 1/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 23:30:02,516 [main.py:get_iosxr_memory_info:206] Retrying in 2 seconds...
INFO 2023-08-15 23:30:04,519 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-15 23:30:09,321 [main.py:get_iosxr_memory_info:209] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts.
ERROR 2023-08-15 23:30:09,324 [main.py:get_iosxr_memory_info:234] Error connecting or gather device xr1
ERROR 2023-08-15 23:30:09,408 [main.py:get_iosxr_memory_info:209] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts.
ERROR 2023-08-15 23:30:09,409 [main.py:get_iosxr_memory_info:234] Error connecting or gather device xr2
ERROR 2023-08-15 23:30:36,577 [main.py:get_iosxr_memory_info:205] Connection attempt 2/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-15 23:30:36,579 [main.py:get_iosxr_memory_info:206] Retrying in 2 seconds...
INFO 2023-08-15 23:30:38,581 [main.py:get_iosxr_memory_info:190] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-15 23:31:10,639 [main.py:get_iosxr_memory_info:209] Failed to establish connection to xr3 (198.18.0.133) after 3 attempts.
ERROR 2023-08-15 23:31:10,641 [main.py:get_iosxr_memory_info:234] Error connecting or gather device xr3
INFO 2023-08-15 23:31:10,643 [main.py:getMemmoryUtils:475] Get Memmory Utilization - execution completed.
INFO 2023-08-15 23:31:10,646 [main.py:getMemmoryUtils:478] Sort Output Data - execution completed.
INFO 2023-08-15 23:31:10,647 [main.py:getMemmoryUtils:479] Total Executed Get Memory Device is IOS_XE:3 IOS_XR:3 IOS:0 NXOS:0 and Total Device is 6
INFO 2023-08-16 18:40:27,994 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 1
INFO 2023-08-16 18:40:28,097 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 1
INFO 2023-08-16 18:40:28,200 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 1
INFO 2023-08-16 18:40:28,305 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 1
INFO 2023-08-16 18:40:28,410 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 1
INFO 2023-08-16 18:40:28,513 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 1
ERROR 2023-08-16 18:40:42,100 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:42,102 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:42,175 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:42,177 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:42,287 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:42,289 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:42,387 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:42,388 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:42,490 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:42,492 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:42,589 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:42,590 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:40:44,107 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 2
INFO 2023-08-16 18:40:44,187 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 2
INFO 2023-08-16 18:40:44,290 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 2
INFO 2023-08-16 18:40:44,390 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 2
INFO 2023-08-16 18:40:44,496 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 2
INFO 2023-08-16 18:40:44,595 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-16 18:40:58,202 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:58,205 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:58,258 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:58,260 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:58,365 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:58,367 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:58,480 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:58,482 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:58,576 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:58,578 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:40:58,676 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr3 (198.18.0.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:40:58,678 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:41:00,207 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 3
INFO 2023-08-16 18:41:00,263 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 3
INFO 2023-08-16 18:41:00,371 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 3
INFO 2023-08-16 18:41:00,485 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 3
INFO 2023-08-16 18:41:00,580 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 3
INFO 2023-08-16 18:41:00,682 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-16 18:41:14,288 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe1 (198.18.0.121) after 3 attempts.
ERROR 2023-08-16 18:41:14,300 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe1 try Nemiko IOSXE Function
INFO 2023-08-16 18:41:14,302 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-16 18:41:14,332 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe2 (198.18.0.122) after 3 attempts.
ERROR 2023-08-16 18:41:14,334 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe2 try Nemiko IOSXE Function
INFO 2023-08-16 18:41:14,336 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
ERROR 2023-08-16 18:41:14,445 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe3 (198.18.0.123) after 3 attempts.
ERROR 2023-08-16 18:41:14,447 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe3 try Nemiko IOSXE Function
INFO 2023-08-16 18:41:14,449 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:41:14,562 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:41:14,565 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr1 using IOSXR Pyats Function
ERROR 2023-08-16 18:41:14,658 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:41:14,661 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr2 using IOSXR Pyats Function
ERROR 2023-08-16 18:41:14,747 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr3 (198.18.0.133) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:41:14,749 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr3 using IOSXR Pyats Function
ERROR 2023-08-16 18:41:17,355 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:41:17,358 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:41:17,366 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:41:17,369 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:41:17,484 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:41:17,486 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:41:19,360 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:41:19,375 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:41:19,490 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:41:22,398 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:41:22,400 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:41:22,420 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:41:22,422 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:41:22,525 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:41:22,526 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:41:24,405 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:41:24,427 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:41:24,531 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:41:27,438 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:41:27,440 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.121 using IOSXE Netmiko Function
ERROR 2023-08-16 18:41:27,458 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:41:27,460 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.122 using IOSXE Netmiko Function
ERROR 2023-08-16 18:41:27,562 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:41:27,564 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.123 using IOSXE Netmiko Function
INFO 2023-08-16 18:41:27,565 [main.py:getMemmoryUtils:502] Get Memmory Utilization - execution completed.
INFO 2023-08-16 18:41:27,567 [main.py:getMemmoryUtils:505] Sort Output Data - execution completed.
INFO 2023-08-16 18:41:27,568 [main.py:getMemmoryUtils:506] Total Executed Get Memory Device is IOS_XE:3 IOS_XR:3 IOS:0 NXOS:0 and Total Device is 6
INFO 2023-08-16 18:46:48,127 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 1
INFO 2023-08-16 18:46:48,229 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 1
INFO 2023-08-16 18:46:48,335 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 1
INFO 2023-08-16 18:46:48,438 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 1
INFO 2023-08-16 18:46:48,543 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 1
INFO 2023-08-16 18:46:48,646 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 1
INFO 2023-08-16 18:46:48,749 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 1
INFO 2023-08-16 18:46:48,852 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 1
INFO 2023-08-16 18:46:48,957 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 1
ERROR 2023-08-16 18:47:02,207 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios1 (198.18.3.131): failed to connect to ios1
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,210 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,294 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios2 (198.18.3.132): failed to connect to ios2
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,297 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,403 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios3 (198.18.3.133): failed to connect to ios3
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,405 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,521 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,523 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,613 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,615 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,722 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,724 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,819 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,820 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:02,915 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:02,916 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:03,047 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr3 (198.18.3.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:03,049 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:47:04,215 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 2
INFO 2023-08-16 18:47:04,298 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 2
INFO 2023-08-16 18:47:04,408 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 2
INFO 2023-08-16 18:47:04,527 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 2
INFO 2023-08-16 18:47:04,619 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 2
INFO 2023-08-16 18:47:04,726 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 2
INFO 2023-08-16 18:47:04,822 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 2
INFO 2023-08-16 18:47:04,918 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 2
INFO 2023-08-16 18:47:05,051 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-16 18:47:18,296 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios1 (198.18.3.131): failed to connect to ios1
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,298 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,371 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios2 (198.18.3.132): failed to connect to ios2
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,372 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,490 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios3 (198.18.3.133): failed to connect to ios3
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,491 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,612 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,614 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,691 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,692 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,807 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,809 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,893 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,895 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:18,990 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:18,992 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:47:19,130 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr3 (198.18.3.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:47:19,132 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:47:20,302 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 3
INFO 2023-08-16 18:47:20,374 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 3
INFO 2023-08-16 18:47:20,494 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 3
INFO 2023-08-16 18:47:20,615 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 3
INFO 2023-08-16 18:47:20,696 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 3
INFO 2023-08-16 18:47:20,813 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 3
INFO 2023-08-16 18:47:20,897 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 3
INFO 2023-08-16 18:47:20,995 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 3
INFO 2023-08-16 18:47:21,134 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-16 18:47:34,377 [main.py:get_ios_memory_info:288] Failed to establish connection to ios1 (198.18.3.131) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:47:34,381 [main.py:get_ios_memory_info:314] Error connecting or gather device ios1 Pyats IOS Function
ERROR 2023-08-16 18:47:34,453 [main.py:get_ios_memory_info:288] Failed to establish connection to ios2 (198.18.3.132) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:47:34,455 [main.py:get_ios_memory_info:314] Error connecting or gather device ios2 Pyats IOS Function
ERROR 2023-08-16 18:47:34,564 [main.py:get_ios_memory_info:288] Failed to establish connection to ios3 (198.18.3.133) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:47:34,566 [main.py:get_ios_memory_info:314] Error connecting or gather device ios3 Pyats IOS Function
ERROR 2023-08-16 18:47:34,702 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe1 (198.18.0.121) after 3 attempts.
ERROR 2023-08-16 18:47:34,704 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe1 try Nemiko IOSXE Function
INFO 2023-08-16 18:47:34,705 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-16 18:47:34,773 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe2 (198.18.0.122) after 3 attempts.
ERROR 2023-08-16 18:47:34,775 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe2 try Nemiko IOSXE Function
INFO 2023-08-16 18:47:34,777 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
ERROR 2023-08-16 18:47:34,883 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe3 (198.18.0.123) after 3 attempts.
ERROR 2023-08-16 18:47:34,884 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe3 try Nemiko IOSXE Function
INFO 2023-08-16 18:47:34,886 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:47:34,974 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:47:34,977 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr1 using IOSXR Pyats Function
ERROR 2023-08-16 18:47:35,067 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:47:35,069 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr2 using IOSXR Pyats Function
ERROR 2023-08-16 18:47:35,211 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr3 (198.18.3.133) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:47:35,213 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr3 using IOSXR Pyats Function
ERROR 2023-08-16 18:47:37,741 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:47:37,743 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:47:37,812 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:47:37,814 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:47:37,921 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:47:37,925 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:47:39,747 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:47:39,819 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:47:39,931 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:47:42,779 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:47:42,780 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:47:42,850 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:47:42,852 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:47:42,964 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:47:42,966 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:47:44,784 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:47:44,856 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:47:44,971 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:47:47,824 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:47:47,825 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.121 using IOSXE Netmiko Function
ERROR 2023-08-16 18:47:47,892 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:47:47,894 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.122 using IOSXE Netmiko Function
ERROR 2023-08-16 18:47:48,012 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:47:48,014 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.123 using IOSXE Netmiko Function
INFO 2023-08-16 18:47:48,016 [main.py:getMemmoryUtils:502] Get Memmory Utilization - execution completed.
INFO 2023-08-16 18:47:48,018 [main.py:getMemmoryUtils:505] Sort Output Data - execution completed.
INFO 2023-08-16 18:47:48,019 [main.py:getMemmoryUtils:506] Total Executed Get Memory Device is IOS_XE:3 IOS_XR:3 IOS:3 NXOS:0 and Total Device is 9
INFO 2023-08-16 18:49:10,799 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 1
INFO 2023-08-16 18:49:10,901 [main.py:get_ios_memory_info:268] Initiate connection to Device ios11 attempt 1
INFO 2023-08-16 18:49:11,007 [main.py:get_ios_memory_info:268] Initiate connection to Device ios12 attempt 1
INFO 2023-08-16 18:49:11,111 [main.py:get_ios_memory_info:268] Initiate connection to Device ios13 attempt 1
INFO 2023-08-16 18:49:11,218 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 1
INFO 2023-08-16 18:49:11,322 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 1
INFO 2023-08-16 18:49:11,425 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox1 attempt 1
INFO 2023-08-16 18:49:11,529 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox11 attempt 1
INFO 2023-08-16 18:49:11,632 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox12 attempt 1
INFO 2023-08-16 18:49:11,733 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox13 attempt 1
INFO 2023-08-16 18:49:11,838 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox2 attempt 1
INFO 2023-08-16 18:49:11,940 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox3 attempt 1
INFO 2023-08-16 18:49:12,046 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 1
INFO 2023-08-16 18:49:12,149 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe11 attempt 1
INFO 2023-08-16 18:49:12,252 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe12 attempt 1
INFO 2023-08-16 18:49:12,354 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe13 attempt 1
INFO 2023-08-16 18:49:12,458 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 1
INFO 2023-08-16 18:49:12,562 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 1
INFO 2023-08-16 18:49:12,664 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 1
INFO 2023-08-16 18:49:12,767 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr11 attempt 1
INFO 2023-08-16 18:49:12,871 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr12 attempt 1
INFO 2023-08-16 18:49:12,980 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr13 attempt 1
INFO 2023-08-16 18:49:13,085 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 1
INFO 2023-08-16 18:49:13,189 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 1
ERROR 2023-08-16 18:49:24,875 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios1 (198.18.3.131): failed to connect to ios1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:24,878 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:24,981 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios11 (198.18.3.131): failed to connect to ios11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:24,983 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,078 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios12 (198.18.3.132): failed to connect to ios12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,079 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,195 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios13 (198.18.3.133): failed to connect to ios13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,196 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,295 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios2 (198.18.3.132): failed to connect to ios2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,296 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,412 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios3 (198.18.3.133): failed to connect to ios3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,414 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,512 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox1 (198.18.3.131): failed to connect to nsox1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,514 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,611 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox11 (198.18.3.131): failed to connect to nsox11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,613 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,706 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox12 (198.18.3.132): failed to connect to nsox12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,708 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,806 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox13 (198.18.3.133): failed to connect to nsox13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,809 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:25,923 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox2 (198.18.3.132): failed to connect to nsox2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:25,925 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,020 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox3 (198.18.3.133): failed to connect to nsox3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,021 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,123 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,125 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,240 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe11 (198.18.0.121): failed to connect to xe11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,242 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,327 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe12 (198.18.0.122): failed to connect to xe12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,328 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,443 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe13 (198.18.0.123): failed to connect to xe13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,445 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,543 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,545 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,650 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,651 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,749 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,750 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:26,831 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr11 (198.18.0.131): failed to connect to xr11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,833 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:26,882 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 2
ERROR 2023-08-16 18:49:26,947 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr12 (198.18.0.132): failed to connect to xr12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:26,950 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:26,986 [main.py:get_ios_memory_info:268] Initiate connection to Device ios11 attempt 2
ERROR 2023-08-16 18:49:27,047 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr13 (198.18.3.133): failed to connect to xr13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:27,053 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:27,083 [main.py:get_ios_memory_info:268] Initiate connection to Device ios12 attempt 2
ERROR 2023-08-16 18:49:27,166 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:27,169 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:27,199 [main.py:get_ios_memory_info:268] Initiate connection to Device ios13 attempt 2
ERROR 2023-08-16 18:49:27,275 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr3 (198.18.3.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:27,278 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:27,301 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 2
INFO 2023-08-16 18:49:27,419 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 2
INFO 2023-08-16 18:49:27,518 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox1 attempt 2
INFO 2023-08-16 18:49:27,615 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox11 attempt 2
INFO 2023-08-16 18:49:27,711 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox12 attempt 2
INFO 2023-08-16 18:49:27,811 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox13 attempt 2
INFO 2023-08-16 18:49:27,928 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox2 attempt 2
INFO 2023-08-16 18:49:28,024 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox3 attempt 2
INFO 2023-08-16 18:49:28,127 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 2
INFO 2023-08-16 18:49:28,246 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe11 attempt 2
INFO 2023-08-16 18:49:28,332 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe12 attempt 2
INFO 2023-08-16 18:49:28,447 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe13 attempt 2
INFO 2023-08-16 18:49:28,550 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 2
INFO 2023-08-16 18:49:28,655 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 2
INFO 2023-08-16 18:49:28,754 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 2
INFO 2023-08-16 18:49:28,837 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr11 attempt 2
INFO 2023-08-16 18:49:28,952 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr12 attempt 2
INFO 2023-08-16 18:49:29,058 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr13 attempt 2
INFO 2023-08-16 18:49:29,173 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 2
INFO 2023-08-16 18:49:29,283 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-16 18:49:40,958 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios1 (198.18.3.131): failed to connect to ios1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:40,960 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,059 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios11 (198.18.3.131): failed to connect to ios11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,061 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,156 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios12 (198.18.3.132): failed to connect to ios12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,158 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,277 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios13 (198.18.3.133): failed to connect to ios13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,279 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,370 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios2 (198.18.3.132): failed to connect to ios2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,372 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,490 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios3 (198.18.3.133): failed to connect to ios3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,492 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,584 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox1 (198.18.3.131): failed to connect to nsox1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,586 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,692 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox11 (198.18.3.131): failed to connect to nsox11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,694 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,786 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox12 (198.18.3.132): failed to connect to nsox12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,788 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:41,888 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox13 (198.18.3.133): failed to connect to nsox13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:41,891 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,003 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox2 (198.18.3.132): failed to connect to nsox2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,005 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,105 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox3 (198.18.3.133): failed to connect to nsox3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,107 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,211 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,213 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,321 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe11 (198.18.0.121): failed to connect to xe11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,324 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,391 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe12 (198.18.0.122): failed to connect to xe12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,393 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,512 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe13 (198.18.0.123): failed to connect to xe13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,514 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,627 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,629 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,737 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,740 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,827 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,829 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:49:42,906 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr11 (198.18.0.131): failed to connect to xr11
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:42,908 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:42,963 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 3
ERROR 2023-08-16 18:49:43,023 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr12 (198.18.0.132): failed to connect to xr12
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:43,026 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:43,064 [main.py:get_ios_memory_info:268] Initiate connection to Device ios11 attempt 3
ERROR 2023-08-16 18:49:43,125 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr13 (198.18.3.133): failed to connect to xr13
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:43,128 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:43,162 [main.py:get_ios_memory_info:268] Initiate connection to Device ios12 attempt 3
ERROR 2023-08-16 18:49:43,239 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:43,242 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:43,282 [main.py:get_ios_memory_info:268] Initiate connection to Device ios13 attempt 3
ERROR 2023-08-16 18:49:43,353 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr3 (198.18.3.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:49:43,356 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:49:43,377 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 3
INFO 2023-08-16 18:49:43,495 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 3
INFO 2023-08-16 18:49:43,590 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox1 attempt 3
INFO 2023-08-16 18:49:43,697 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox11 attempt 3
INFO 2023-08-16 18:49:43,791 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox12 attempt 3
INFO 2023-08-16 18:49:43,894 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox13 attempt 3
INFO 2023-08-16 18:49:44,007 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox2 attempt 3
INFO 2023-08-16 18:49:44,111 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox3 attempt 3
INFO 2023-08-16 18:49:44,216 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 3
INFO 2023-08-16 18:49:44,327 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe11 attempt 3
INFO 2023-08-16 18:49:44,395 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe12 attempt 3
INFO 2023-08-16 18:49:44,518 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe13 attempt 3
INFO 2023-08-16 18:49:44,634 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 3
INFO 2023-08-16 18:49:44,743 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 3
INFO 2023-08-16 18:49:44,831 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 3
INFO 2023-08-16 18:49:44,912 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr11 attempt 3
INFO 2023-08-16 18:49:45,030 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr12 attempt 3
INFO 2023-08-16 18:49:45,131 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr13 attempt 3
INFO 2023-08-16 18:49:45,246 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 3
INFO 2023-08-16 18:49:45,358 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-16 18:49:57,039 [main.py:get_ios_memory_info:288] Failed to establish connection to ios1 (198.18.3.131) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:49:57,041 [main.py:get_ios_memory_info:314] Error connecting or gather device ios1 Pyats IOS Function
ERROR 2023-08-16 18:49:57,139 [main.py:get_ios_memory_info:288] Failed to establish connection to ios11 (198.18.3.131) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:49:57,141 [main.py:get_ios_memory_info:314] Error connecting or gather device ios11 Pyats IOS Function
ERROR 2023-08-16 18:49:57,238 [main.py:get_ios_memory_info:288] Failed to establish connection to ios12 (198.18.3.132) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:49:57,240 [main.py:get_ios_memory_info:314] Error connecting or gather device ios12 Pyats IOS Function
ERROR 2023-08-16 18:49:57,356 [main.py:get_ios_memory_info:288] Failed to establish connection to ios13 (198.18.3.133) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:49:57,358 [main.py:get_ios_memory_info:314] Error connecting or gather device ios13 Pyats IOS Function
ERROR 2023-08-16 18:49:57,472 [main.py:get_ios_memory_info:288] Failed to establish connection to ios2 (198.18.3.132) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:49:57,474 [main.py:get_ios_memory_info:314] Error connecting or gather device ios2 Pyats IOS Function
ERROR 2023-08-16 18:49:57,572 [main.py:get_ios_memory_info:288] Failed to establish connection to ios3 (198.18.3.133) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:49:57,574 [main.py:get_ios_memory_info:314] Error connecting or gather device ios3 Pyats IOS Function
ERROR 2023-08-16 18:49:57,675 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox1 (198.18.3.131) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:49:57,676 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox1
INFO 2023-08-16 18:49:57,678 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.131
ERROR 2023-08-16 18:49:57,775 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox11 (198.18.3.131) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:49:57,777 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox11
INFO 2023-08-16 18:49:57,778 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.131
ERROR 2023-08-16 18:49:57,859 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox12 (198.18.3.132) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:49:57,860 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox12
INFO 2023-08-16 18:49:57,862 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.132
ERROR 2023-08-16 18:49:57,974 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox13 (198.18.3.133) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:49:57,976 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox13
INFO 2023-08-16 18:49:57,978 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.133
ERROR 2023-08-16 18:49:58,081 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox2 (198.18.3.132) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:49:58,084 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox2
INFO 2023-08-16 18:49:58,085 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.132
ERROR 2023-08-16 18:49:58,185 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox3 (198.18.3.133) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:49:58,187 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox3
INFO 2023-08-16 18:49:58,188 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.133
ERROR 2023-08-16 18:49:58,291 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe1 (198.18.0.121) after 3 attempts.
ERROR 2023-08-16 18:49:58,293 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe1 try Nemiko IOSXE Function
INFO 2023-08-16 18:49:58,295 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-16 18:49:58,394 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe11 (198.18.0.121) after 3 attempts.
ERROR 2023-08-16 18:49:58,396 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe11 try Nemiko IOSXE Function
INFO 2023-08-16 18:49:58,398 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-16 18:49:58,475 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe12 (198.18.0.122) after 3 attempts.
ERROR 2023-08-16 18:49:58,476 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe12 try Nemiko IOSXE Function
INFO 2023-08-16 18:49:58,477 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
ERROR 2023-08-16 18:49:58,599 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe13 (198.18.0.123) after 3 attempts.
ERROR 2023-08-16 18:49:58,601 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe13 try Nemiko IOSXE Function
INFO 2023-08-16 18:49:58,602 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:49:58,705 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe2 (198.18.0.122) after 3 attempts.
ERROR 2023-08-16 18:49:58,707 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe2 try Nemiko IOSXE Function
INFO 2023-08-16 18:49:58,709 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
ERROR 2023-08-16 18:49:58,814 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe3 (198.18.0.123) after 3 attempts.
ERROR 2023-08-16 18:49:58,816 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe3 try Nemiko IOSXE Function
INFO 2023-08-16 18:49:58,818 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:49:58,895 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:49:58,896 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr1 using IOSXR Pyats Function
ERROR 2023-08-16 18:49:58,979 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr11 (198.18.0.131) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:49:58,981 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr11 using IOSXR Pyats Function
ERROR 2023-08-16 18:49:59,107 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr12 (198.18.0.132) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:49:59,109 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr12 using IOSXR Pyats Function
ERROR 2023-08-16 18:49:59,202 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr13 (198.18.3.133) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:49:59,204 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr13 using IOSXR Pyats Function
ERROR 2023-08-16 18:49:59,315 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:49:59,317 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr2 using IOSXR Pyats Function
ERROR 2023-08-16 18:49:59,425 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr3 (198.18.3.133) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:49:59,427 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr3 using IOSXR Pyats Function
ERROR 2023-08-16 18:50:00,713 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:00,715 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:50:00,804 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:00,806 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:50:00,896 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:00,898 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:50:01,018 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,020 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:50:01,120 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,122 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:50:01,226 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,228 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:50:01,331 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,333 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:50:01,431 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,433 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:50:01,512 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,513 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:50:01,642 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,644 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
ERROR 2023-08-16 18:50:01,734 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,736 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:50:01,846 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:01,849 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:50:02,719 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.131
INFO 2023-08-16 18:50:02,810 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.131
INFO 2023-08-16 18:50:02,902 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.132
INFO 2023-08-16 18:50:03,024 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.133
INFO 2023-08-16 18:50:03,126 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.132
INFO 2023-08-16 18:50:03,229 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.133
INFO 2023-08-16 18:50:03,336 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:03,435 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:03,518 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:03,647 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:03,741 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:03,852 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:50:05,744 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:05,747 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:50:05,837 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:05,839 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:50:05,930 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:05,931 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:50:06,052 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,054 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:50:06,156 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,157 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:50:06,257 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,260 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:50:06,361 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,363 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:50:06,505 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,507 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:50:06,544 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,546 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:50:06,676 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,677 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
ERROR 2023-08-16 18:50:06,769 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,770 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:50:06,882 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:50:06,884 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:50:07,750 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.131
INFO 2023-08-16 18:50:07,843 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.131
INFO 2023-08-16 18:50:07,934 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.132
INFO 2023-08-16 18:50:08,058 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.133
INFO 2023-08-16 18:50:08,162 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.132
INFO 2023-08-16 18:50:08,262 [main.py:get_nxos_memory_info:385] Establishing Netmiko connection for 198.18.3.133
INFO 2023-08-16 18:50:08,367 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:08,511 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:08,550 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:08,682 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:08,774 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:50:08,886 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:50:10,778 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:10,781 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox1 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:50:10,874 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:10,876 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox11 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:50:10,964 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:10,966 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox12 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:50:11,088 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,090 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox13 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:50:11,195 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,197 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox2 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:50:11,291 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,294 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox3 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:50:11,397 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,399 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.121 using IOSXE Netmiko Function
ERROR 2023-08-16 18:50:11,540 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,541 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.121 using IOSXE Netmiko Function
ERROR 2023-08-16 18:50:11,584 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,585 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.122 using IOSXE Netmiko Function
ERROR 2023-08-16 18:50:11,715 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,716 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.123 using IOSXE Netmiko Function
ERROR 2023-08-16 18:50:11,802 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,804 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.122 using IOSXE Netmiko Function
ERROR 2023-08-16 18:50:11,916 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:50:11,917 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.123 using IOSXE Netmiko Function
INFO 2023-08-16 18:50:11,919 [main.py:getMemmoryUtils:502] Get Memmory Utilization - execution completed.
INFO 2023-08-16 18:50:11,922 [main.py:getMemmoryUtils:505] Sort Output Data - execution completed.
INFO 2023-08-16 18:50:11,924 [main.py:getMemmoryUtils:506] Total Executed Get Memory Device is IOS_XE:6 IOS_XR:6 IOS:6 NXOS:6 and Total Device is 24
INFO 2023-08-16 18:52:00,674 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 1
INFO 2023-08-16 18:52:00,775 [main.py:get_ios_memory_info:268] Initiate connection to Device ios11 attempt 1
INFO 2023-08-16 18:52:00,881 [main.py:get_ios_memory_info:268] Initiate connection to Device ios12 attempt 1
INFO 2023-08-16 18:52:00,986 [main.py:get_ios_memory_info:268] Initiate connection to Device ios13 attempt 1
INFO 2023-08-16 18:52:01,091 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 1
INFO 2023-08-16 18:52:01,192 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 1
INFO 2023-08-16 18:52:01,296 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox1 attempt 1
INFO 2023-08-16 18:52:01,398 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox11 attempt 1
INFO 2023-08-16 18:52:01,502 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox12 attempt 1
INFO 2023-08-16 18:52:01,607 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox13 attempt 1
INFO 2023-08-16 18:52:01,711 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox2 attempt 1
INFO 2023-08-16 18:52:01,817 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox3 attempt 1
INFO 2023-08-16 18:52:01,923 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 1
INFO 2023-08-16 18:52:02,026 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe11 attempt 1
INFO 2023-08-16 18:52:02,130 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe12 attempt 1
INFO 2023-08-16 18:52:02,234 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe13 attempt 1
INFO 2023-08-16 18:52:02,339 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 1
INFO 2023-08-16 18:52:02,443 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 1
INFO 2023-08-16 18:52:02,548 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 1
INFO 2023-08-16 18:52:02,655 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr11 attempt 1
INFO 2023-08-16 18:52:02,759 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr12 attempt 1
INFO 2023-08-16 18:52:02,863 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr13 attempt 1
INFO 2023-08-16 18:52:02,967 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 1
INFO 2023-08-16 18:52:03,073 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 1
ERROR 2023-08-16 18:52:14,741 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios1 (198.18.3.131): failed to connect to ios1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:14,743 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:14,847 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios11 (198.18.3.131): failed to connect to ios11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:14,848 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:14,959 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios12 (198.18.3.132): failed to connect to ios12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:14,961 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,069 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios13 (198.18.3.133): failed to connect to ios13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,071 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,178 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios2 (198.18.3.132): failed to connect to ios2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,180 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,266 [main.py:get_ios_memory_info:284] Connection attempt 1/3 failed for ios3 (198.18.3.133): failed to connect to ios3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,268 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,370 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox1 (198.18.3.131): failed to connect to nsox1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,372 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,467 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox11 (198.18.3.131): failed to connect to nsox11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,468 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,575 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox12 (198.18.3.132): failed to connect to nsox12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,577 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,685 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox13 (198.18.3.133): failed to connect to nsox13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,687 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,787 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox2 (198.18.3.132): failed to connect to nsox2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,789 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:15,895 [main.py:get_nxos_memory_info:344] Connection attempt 1/3 failed for nsox3 (198.18.3.133): failed to connect to nsox3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:15,897 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,000 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,002 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,099 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe11 (198.18.0.121): failed to connect to xe11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,100 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,211 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe12 (198.18.0.122): failed to connect to xe12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,213 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,305 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe13 (198.18.0.123): failed to connect to xe13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,307 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,419 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,420 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,516 [main.py:get_iosxe_memory_info:107] Connection attempt 1/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,519 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,619 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,621 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:16,728 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr11 (198.18.0.131): failed to connect to xr11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,729 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:16,746 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 2
ERROR 2023-08-16 18:52:16,844 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr12 (198.18.0.132): failed to connect to xr12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,847 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:16,851 [main.py:get_ios_memory_info:268] Initiate connection to Device ios11 attempt 2
ERROR 2023-08-16 18:52:16,951 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr13 (198.18.3.133): failed to connect to xr13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:16,953 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:16,963 [main.py:get_ios_memory_info:268] Initiate connection to Device ios12 attempt 2
ERROR 2023-08-16 18:52:17,047 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:17,049 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:17,075 [main.py:get_ios_memory_info:268] Initiate connection to Device ios13 attempt 2
ERROR 2023-08-16 18:52:17,159 [main.py:get_iosxr_memory_info:228] Connection attempt 1/3 failed for xr3 (198.18.3.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:17,162 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:17,183 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 2
INFO 2023-08-16 18:52:17,270 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 2
INFO 2023-08-16 18:52:17,375 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox1 attempt 2
INFO 2023-08-16 18:52:17,472 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox11 attempt 2
INFO 2023-08-16 18:52:17,580 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox12 attempt 2
INFO 2023-08-16 18:52:17,689 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox13 attempt 2
INFO 2023-08-16 18:52:17,794 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox2 attempt 2
INFO 2023-08-16 18:52:17,899 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox3 attempt 2
INFO 2023-08-16 18:52:18,005 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 2
INFO 2023-08-16 18:52:18,103 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe11 attempt 2
INFO 2023-08-16 18:52:18,215 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe12 attempt 2
INFO 2023-08-16 18:52:18,309 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe13 attempt 2
INFO 2023-08-16 18:52:18,424 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 2
INFO 2023-08-16 18:52:18,522 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 2
INFO 2023-08-16 18:52:18,623 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 2
INFO 2023-08-16 18:52:18,732 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr11 attempt 2
INFO 2023-08-16 18:52:18,851 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr12 attempt 2
INFO 2023-08-16 18:52:18,954 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr13 attempt 2
INFO 2023-08-16 18:52:19,051 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 2
INFO 2023-08-16 18:52:19,166 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 2
ERROR 2023-08-16 18:52:30,819 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios1 (198.18.3.131): failed to connect to ios1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:30,822 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:30,925 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios11 (198.18.3.131): failed to connect to ios11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:30,926 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,041 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios12 (198.18.3.132): failed to connect to ios12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,043 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,143 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios13 (198.18.3.133): failed to connect to ios13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,145 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,258 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios2 (198.18.3.132): failed to connect to ios2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,260 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,346 [main.py:get_ios_memory_info:284] Connection attempt 2/3 failed for ios3 (198.18.3.133): failed to connect to ios3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,348 [main.py:get_ios_memory_info:285] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,447 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox1 (198.18.3.131): failed to connect to nsox1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,448 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,551 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox11 (198.18.3.131): failed to connect to nsox11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,553 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,642 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox12 (198.18.3.132): failed to connect to nsox12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,643 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,765 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox13 (198.18.3.133): failed to connect to nsox13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,767 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,875 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox2 (198.18.3.132): failed to connect to nsox2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,876 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:31,966 [main.py:get_nxos_memory_info:344] Connection attempt 2/3 failed for nsox3 (198.18.3.133): failed to connect to nsox3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:31,968 [main.py:get_nxos_memory_info:345] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,087 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe1 (198.18.0.121): failed to connect to xe1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,089 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,175 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe11 (198.18.0.121): failed to connect to xe11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,178 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,287 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe12 (198.18.0.122): failed to connect to xe12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,289 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,388 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe13 (198.18.0.123): failed to connect to xe13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,389 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,493 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe2 (198.18.0.122): failed to connect to xe2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,495 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,599 [main.py:get_iosxe_memory_info:107] Connection attempt 2/3 failed for xe3 (198.18.0.123): failed to connect to xe3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,600 [main.py:get_iosxe_memory_info:108] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,695 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr1 (198.18.0.131): failed to connect to xr1
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,697 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
ERROR 2023-08-16 18:52:32,799 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr11 (198.18.0.131): failed to connect to xr11
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,800 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:32,826 [main.py:get_ios_memory_info:268] Initiate connection to Device ios1 attempt 3
ERROR 2023-08-16 18:52:32,919 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr12 (198.18.0.132): failed to connect to xr12
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:32,921 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:32,931 [main.py:get_ios_memory_info:268] Initiate connection to Device ios11 attempt 3
ERROR 2023-08-16 18:52:33,026 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr13 (198.18.3.133): failed to connect to xr13
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:33,029 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:33,045 [main.py:get_ios_memory_info:268] Initiate connection to Device ios12 attempt 3
ERROR 2023-08-16 18:52:33,123 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr2 (198.18.0.132): failed to connect to xr2
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:33,126 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:33,147 [main.py:get_ios_memory_info:268] Initiate connection to Device ios13 attempt 3
ERROR 2023-08-16 18:52:33,231 [main.py:get_iosxr_memory_info:228] Connection attempt 2/3 failed for xr3 (198.18.3.133): failed to connect to xr3
Failed while bringing device to "any" state
INFO 2023-08-16 18:52:33,234 [main.py:get_iosxr_memory_info:229] Retrying in 2 seconds...
INFO 2023-08-16 18:52:33,263 [main.py:get_ios_memory_info:268] Initiate connection to Device ios2 attempt 3
INFO 2023-08-16 18:52:33,350 [main.py:get_ios_memory_info:268] Initiate connection to Device ios3 attempt 3
INFO 2023-08-16 18:52:33,451 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox1 attempt 3
INFO 2023-08-16 18:52:33,557 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox11 attempt 3
INFO 2023-08-16 18:52:33,647 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox12 attempt 3
INFO 2023-08-16 18:52:33,771 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox13 attempt 3
INFO 2023-08-16 18:52:33,879 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox2 attempt 3
INFO 2023-08-16 18:52:33,971 [main.py:get_nxos_memory_info:329] Initiate connection to Device nsox3 attempt 3
INFO 2023-08-16 18:52:34,091 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe1 attempt 3
INFO 2023-08-16 18:52:34,179 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe11 attempt 3
INFO 2023-08-16 18:52:34,294 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe12 attempt 3
INFO 2023-08-16 18:52:34,394 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe13 attempt 3
INFO 2023-08-16 18:52:34,497 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe2 attempt 3
INFO 2023-08-16 18:52:34,603 [main.py:get_iosxe_memory_info:91] Initiate connection to Device xe3 attempt 3
INFO 2023-08-16 18:52:34,700 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr1 attempt 3
INFO 2023-08-16 18:52:34,804 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr11 attempt 3
INFO 2023-08-16 18:52:34,923 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr12 attempt 3
INFO 2023-08-16 18:52:35,033 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr13 attempt 3
INFO 2023-08-16 18:52:35,130 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr2 attempt 3
INFO 2023-08-16 18:52:35,239 [main.py:get_iosxr_memory_info:212] Initiate connection to Device xr3 attempt 3
ERROR 2023-08-16 18:52:46,898 [main.py:get_ios_memory_info:288] Failed to establish connection to ios1 (198.18.3.131) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:52:46,901 [main.py:get_ios_memory_info:314] Error connecting or gather device ios1 Pyats IOS Function
ERROR 2023-08-16 18:52:47,007 [main.py:get_ios_memory_info:288] Failed to establish connection to ios11 (198.18.3.131) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:52:47,009 [main.py:get_ios_memory_info:314] Error connecting or gather device ios11 Pyats IOS Function
ERROR 2023-08-16 18:52:47,113 [main.py:get_ios_memory_info:288] Failed to establish connection to ios12 (198.18.3.132) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:52:47,114 [main.py:get_ios_memory_info:314] Error connecting or gather device ios12 Pyats IOS Function
ERROR 2023-08-16 18:52:47,224 [main.py:get_ios_memory_info:288] Failed to establish connection to ios13 (198.18.3.133) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:52:47,226 [main.py:get_ios_memory_info:314] Error connecting or gather device ios13 Pyats IOS Function
ERROR 2023-08-16 18:52:47,334 [main.py:get_ios_memory_info:288] Failed to establish connection to ios2 (198.18.3.132) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:52:47,337 [main.py:get_ios_memory_info:314] Error connecting or gather device ios2 Pyats IOS Function
ERROR 2023-08-16 18:52:47,416 [main.py:get_ios_memory_info:288] Failed to establish connection to ios3 (198.18.3.133) after 3 attempts using Pyats IOS Function.
ERROR 2023-08-16 18:52:47,418 [main.py:get_ios_memory_info:314] Error connecting or gather device ios3 Pyats IOS Function
ERROR 2023-08-16 18:52:47,551 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox1 (198.18.3.131) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:52:47,553 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox1
INFO 2023-08-16 18:52:47,555 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.131 using Netmiko NXOS Function
ERROR 2023-08-16 18:52:47,626 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox11 (198.18.3.131) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:52:47,628 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox11
INFO 2023-08-16 18:52:47,630 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.131 using Netmiko NXOS Function
ERROR 2023-08-16 18:52:47,726 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox12 (198.18.3.132) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:52:47,728 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox12
INFO 2023-08-16 18:52:47,730 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.132 using Netmiko NXOS Function
ERROR 2023-08-16 18:52:47,851 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox13 (198.18.3.133) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:52:47,852 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox13
INFO 2023-08-16 18:52:47,854 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.133 using Netmiko NXOS Function
ERROR 2023-08-16 18:52:47,959 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox2 (198.18.3.132) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:52:47,960 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox2
INFO 2023-08-16 18:52:47,961 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.132 using Netmiko NXOS Function
ERROR 2023-08-16 18:52:48,039 [main.py:get_nxos_memory_info:348] Failed to establish connection to nsox3 (198.18.3.133) after 3 attempts using NXOS Function.
ERROR 2023-08-16 18:52:48,042 [main.py:get_nxos_memory_info:374] Failed to Connect Using Main Function Pyats NSOX for nsox3
INFO 2023-08-16 18:52:48,044 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.133 using Netmiko NXOS Function
ERROR 2023-08-16 18:52:48,178 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe1 (198.18.0.121) after 3 attempts.
ERROR 2023-08-16 18:52:48,180 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe1 try Nemiko IOSXE Function
INFO 2023-08-16 18:52:48,182 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:48,246 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe11 (198.18.0.121) after 3 attempts.
ERROR 2023-08-16 18:52:48,248 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe11 try Nemiko IOSXE Function
INFO 2023-08-16 18:52:48,250 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:48,361 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe12 (198.18.0.122) after 3 attempts.
ERROR 2023-08-16 18:52:48,362 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe12 try Nemiko IOSXE Function
INFO 2023-08-16 18:52:48,364 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:48,471 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe13 (198.18.0.123) after 3 attempts.
ERROR 2023-08-16 18:52:48,474 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe13 try Nemiko IOSXE Function
INFO 2023-08-16 18:52:48,475 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:48,566 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe2 (198.18.0.122) after 3 attempts.
ERROR 2023-08-16 18:52:48,568 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe2 try Nemiko IOSXE Function
INFO 2023-08-16 18:52:48,570 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:48,667 [main.py:get_iosxe_memory_info:111] Failed to establish connection to xe3 (198.18.0.123) after 3 attempts.
ERROR 2023-08-16 18:52:48,669 [main.py:get_iosxe_memory_info:136] Failed to Connect Using Main Function pyats iosxe for xe3 try Nemiko IOSXE Function
INFO 2023-08-16 18:52:48,670 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:48,787 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr1 (198.18.0.131) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:52:48,789 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr1 using IOSXR Pyats Function
ERROR 2023-08-16 18:52:48,874 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr11 (198.18.0.131) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:52:48,876 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr11 using IOSXR Pyats Function
ERROR 2023-08-16 18:52:48,991 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr12 (198.18.0.132) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:52:48,993 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr12 using IOSXR Pyats Function
ERROR 2023-08-16 18:52:49,102 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr13 (198.18.3.133) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:52:49,104 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr13 using IOSXR Pyats Function
ERROR 2023-08-16 18:52:49,202 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr2 (198.18.0.132) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:52:49,204 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr2 using IOSXR Pyats Function
ERROR 2023-08-16 18:52:49,325 [main.py:get_iosxr_memory_info:232] Failed to establish connection to xr3 (198.18.3.133) after 3 attempts using IOSXR Pyats Function.
ERROR 2023-08-16 18:52:49,327 [main.py:get_iosxr_memory_info:259] Error connecting or gather device xr3 using IOSXR Pyats Function
ERROR 2023-08-16 18:52:50,583 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:50,585 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:52:50,656 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:50,658 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:52:50,764 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:50,766 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:52:50,890 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:50,892 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:52:50,993 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:50,995 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:52:51,081 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 1/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,082 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:52:51,219 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,221 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:52:51,285 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,287 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:52:51,399 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,401 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:52:51,515 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,517 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
ERROR 2023-08-16 18:52:51,604 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,606 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:52:51,704 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 1/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:51,706 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:52:52,590 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.131 using Netmiko NXOS Function
INFO 2023-08-16 18:52:52,662 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.131 using Netmiko NXOS Function
INFO 2023-08-16 18:52:52,770 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.132 using Netmiko NXOS Function
INFO 2023-08-16 18:52:52,896 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.133 using Netmiko NXOS Function
INFO 2023-08-16 18:52:52,999 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.132 using Netmiko NXOS Function
INFO 2023-08-16 18:52:53,086 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.133 using Netmiko NXOS Function
INFO 2023-08-16 18:52:53,226 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:53,290 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:53,405 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:53,519 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:53,610 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:53,710 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:52:55,622 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:55,624 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:52:55,692 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:55,694 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.131 in 2 seconds...
ERROR 2023-08-16 18:52:55,799 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:55,801 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:52:55,921 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:55,924 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:52:56,024 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,026 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.132 in 2 seconds...
ERROR 2023-08-16 18:52:56,115 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 2/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,117 [main.py:get_nxos_memory_info:393] Retrying 198.18.3.133 in 2 seconds...
ERROR 2023-08-16 18:52:56,255 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,257 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:52:56,321 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,323 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.121 in 2 seconds...
ERROR 2023-08-16 18:52:56,444 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,446 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:52:56,548 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,549 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
ERROR 2023-08-16 18:52:56,637 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,639 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.122 in 2 seconds...
ERROR 2023-08-16 18:52:56,737 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 2/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


INFO 2023-08-16 18:52:56,738 [main.py:get_iosxe_memory_info:156] Retrying 198.18.0.123 in 2 seconds...
INFO 2023-08-16 18:52:57,626 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.131 using Netmiko NXOS Function
INFO 2023-08-16 18:52:57,698 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.131 using Netmiko NXOS Function
INFO 2023-08-16 18:52:57,802 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.132 using Netmiko NXOS Function
INFO 2023-08-16 18:52:57,926 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.133 using Netmiko NXOS Function
INFO 2023-08-16 18:52:58,030 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.132 using Netmiko NXOS Function
INFO 2023-08-16 18:52:58,118 [main.py:get_nxos_memory_info:385] Establishing connection for 198.18.3.133 using Netmiko NXOS Function
INFO 2023-08-16 18:52:58,262 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:58,326 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.121 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:58,449 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:58,553 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:58,643 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.122 using Netmiko IOSXE Function
INFO 2023-08-16 18:52:58,742 [main.py:get_iosxe_memory_info:148] Establishing Connection for 198.18.0.123 using Netmiko IOSXE Function
ERROR 2023-08-16 18:53:00,656 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:00,658 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox1 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:53:00,728 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.131: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:00,730 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox11 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:53:00,833 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:00,834 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox12 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:53:00,956 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:00,958 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox13 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:53:01,057 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.132: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,059 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox2 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:53:01,147 [main.py:get_nxos_memory_info:390] Authentication or connection error (attempt 3/3) for device 198.18.3.133: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,149 [main.py:get_nxos_memory_info:396] Maximum retries reached. Unable to establish connection to device nsox3 Using Netmiko NSOX Function.
ERROR 2023-08-16 18:53:01,291 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,294 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.121 using IOSXE Netmiko Function
ERROR 2023-08-16 18:53:01,351 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.121: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,353 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.121 using IOSXE Netmiko Function
ERROR 2023-08-16 18:53:01,481 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,483 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.122 using IOSXE Netmiko Function
ERROR 2023-08-16 18:53:01,583 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,584 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.123 using IOSXE Netmiko Function
ERROR 2023-08-16 18:53:01,674 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.122: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,676 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.122 using IOSXE Netmiko Function
ERROR 2023-08-16 18:53:01,771 [main.py:get_iosxe_memory_info:153] Authentication or connection error (attempt 3/3) for device 198.18.0.123: 
A paramiko SSHException occurred during connection creation:

Error reading SSH protocol banner[Errno 104] Connection reset by peer


ERROR 2023-08-16 18:53:01,772 [main.py:get_iosxe_memory_info:159] Maximum retries reached. Unable to establish connection to device 198.18.0.123 using IOSXE Netmiko Function
INFO 2023-08-16 18:53:01,774 [main.py:getMemmoryUtils:502] Get Memmory Utilization - execution completed.
INFO 2023-08-16 18:53:01,777 [main.py:getMemmoryUtils:505] Sort Output Data - execution completed.
INFO 2023-08-16 18:53:01,779 [main.py:getMemmoryUtils:506] Total Executed Get Memory Device is IOS_XE:6 IOS_XR:6 IOS:6 NXOS:6 and Total Device is 24
INFO 2023-08-22 17:22:10,598 [main.py:getMemmoryUtils:502] Get Memmory Utilization - execution completed.
INFO 2023-08-22 17:22:10,602 [main.py:getMemmoryUtils:505] Sort Output Data - execution completed.
INFO 2023-08-22 17:22:10,603 [main.py:getMemmoryUtils:506] Total Executed Get Memory Device is IOS_XE:0 IOS_XR:0 IOS:0 NXOS:0 and Total Device is 0
